# Generated by Django 2.2.23 on 2021-05-29 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recommender_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('course_provider', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('topics_of_interest', models.CharField(max_length=30, null=True)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender_app.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_list', models.CharField(max_length=30, null=True)),
                ('assessment_question', models.CharField(max_length=30, null=True)),
                ('assessment_answer', models.FileField(null=True, upload_to=recommender_app.models.user_directory_path)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender_app.Course')),
            ],
        ),
    ]
