# Generated by Django 2.2.23 on 2021-05-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0004_auto_20210530_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender_app.Student'),
        ),
    ]
