# Generated by Django 2.2.23 on 2021-05-31 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0007_auto_20210531_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
