# Generated by Django 2.2.23 on 2021-06-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0008_auto_20210531_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(choices=[(1, 'Like'), (-1, 'Dislike')], null=True),
        ),
    ]
