# Generated by Django 2.2.23 on 2021-06-02 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_app', '0009_auto_20210601_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
